### PR TITLE
chore: improve build speed

### PR DESCRIPTION
**Pull request by 634750802**
- [x] use next 12
- [x] use node 16
- [x] remove dependencies of ui/common/datasource
- [x] remove mockApi
- [x] deprecate accounts/strapi/ui-scripts
- [x] setup all environment secrets 8c2c990
- [x] Start from 7fcd183, we need to fix typing issues.
- [x] optimize runtime dependencies 5e5bbf7
- [x] use github actions 35bf663

Side effects:
- Due to `ui-scripts` was deprecated, we need to keep previous build until new ui-scripts finished.
- mockApi was removed, developers should use preview API as dev api. While developing new APIs, we could use `axios-mock`
- strapi would be moved to another repo
- accounts should be moved to a new repo (not planned yet)

### CODE REVIEW

**Comment by 634750802** [comment]
From now, we need fix typing issues

**Comment by 634750802** [comment]
woohoo~

**Comment by xiyan128** [comment]
@634750802 Would it be nice to have [deployment approvals](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) as before?

**Comment by 634750802** [comment]
> @634750802 Would it be nice to have [deployment approvals](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) as before?

Yes, it is configured by [github actions environment](https://docs.github.com/cn/actions/deployment/targeting-different-environments/using-environments-for-deployment)

**Pull request merged**
